### ISSUE TITLE
Fix issue when permissions are set on git-backed config repositories

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#140]
Traceback (most recent call last):
      File "/usr/bin/mcvirt", line 38, in <module>
        parser_object.parse_arguments()
      File "/usr/lib/mcvirt/parser.py", line 833, in parse_arguments
        vm_object.setLockState(LockStates(LockStates.UNLOCKED))
      File "/usr/lib/mcvirt/virtual_machine/virtual_machine.py", line 1278, in setLockState
        (self.getName(), lock_status.name))
      File "/usr/lib/mcvirt/config_file.py", line 52, in updateConfig
        self.setConfigPermissions()
      File "/usr/lib/mcvirt/config_file.py", line 99, in setConfigPermissions
        setPermission(os.path.join(path, 'vm'), directory=True)
      File "/usr/lib/mcvirt/config_file.py", line 89, in setPermission
        os.chown(path, owner, 0)
    OSError: [Errno 2] No such file or directory: '/var/lib/mcvirt/.git/vm'

**Comment by MatthewJohn** [comment]
Fixed in #142
