### ISSUE TITLE
Handle in-use ports during DRBD creation

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#258]
If a port is in use (at at least DRBD thinks it is), the creation will fail with:

    2016-11-25 09:11:29,027 mcvirtd      /usr/lib/mcvirt/system.py 42: runCommand ERROR    Failed system command: /sbin/drbdadm, connect, mcvirt_vm-VMNAME-disk-1
    RC: 10
    Stdout: 
    Stderr: mcvirt_vm-VMNAME-disk-1: Failure: (102) Local address(port) already in use.
    Command 'drbdsetup-84 connect mcvirt_vm-VMNAME-disk-1 ipv4:***:*** ipv4:***:*** --verify-alg=sha1 --after-sb-2pri=disconnect --after-sb-1pri=discard-secondary --after-sb-0pri=discard-zero-changes --shared-secret=*** --cram-hmac-alg=sha1 --ko-count=50 --protocol=C' terminated with exit code 10

    2016-11-25 09:11:31,022 mcvirtd      /usr/lib/mcvirt/rpc/lock.py 83: lock_log_and_call ERROR    An internal MCVirt exception occurred in lock
    2016-11-25 09:11:31,024 mcvirtd      /usr/lib/mcvirt/rpc/lock.py 84: lock_log_and_call ERROR    Traceback (most recent call last):
      File "/usr/lib/mcvirt/rpc/lock.py", line 81, in lock_log_and_call
        response = callback(*args, **kwargs)
      File "/usr/lib/mcvirt/virtual_machine/virtual_machine.py", line 1063, in duplicate
        disk_object.duplicate(new_vm_object)
      File "/usr/lib/mcvirt/virtual_machine/hard_drive/base.py", line 205, in duplicate
        new_disk_object.create(self.getSize())
      File "/usr/lib/mcvirt/virtual_machine/hard_drive/drbd.py", line 369, in create
        self._drbdConnect()
      File "/usr/lib/mcvirt/virtual_machine/hard_drive/drbd.py", line 581, in _drbdConnect
        System.runCommand([NodeDrbd.DrbdADM, 'connect', self.resource_name])
      File "/usr/lib/mcvirt/system.py", line 43, in runCommand
        raise MCVirtCommandException(('External command failure. '
    MCVirtCommandException: External command failure. See MCVirt log for more information

**Comment by MatthewJohn** [comment]
It's probably best to catch this error, obtain the list of used DRBD ports and append it to it and find another port.
Then the DRBD config can be regenerated on both nodes and then connected

**Comment by MatthewJohn** [comment]
If this happens, there is not really an easy way around it, meaning that you cannot create any more DRBD volumes
