### ISSUE TITLE
VMs cannot be registered with LibVirt if the memory for the VM is changed

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#36]
If the amount of memory allocated to a VM is changed:

    mcvirt update <VM Name> --memory 512

When the VM is registered with LibVirt (for example when the VM is migrated), the following exception is thrown:

    >>> vm.register()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/mcvirt/virtual_machine/virtual_machine.py", line 826, in register
        domain_xml_string = ET.tostring(domain_xml.getroot(), encoding='utf8', method='xml')
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
        ElementTree(element).write(file, encoding, method=method)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
        serialize(write, self._root, encoding, qnames, namespaces)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
        _serialize_xml(write, e, encoding, qnames, None)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
        write(_escape_cdata(text, encoding))
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1075, in _escape_cdata
        _raise_serialization_error(text)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1052, in _raise_serialization_error
        "cannot serialize %r (type %s)" % (text, type(text).__name__)
    TypeError: cannot serialize 524288 (type int)

**Comment by MatthewJohn** [comment]
This appears to be due to the memory configuration being stored as a string when the VM is created, but stored as an integer when the memory allocation is modified.

The following change should fix the issue:
    --- a/source/usr/lib/mcvirt/virtual_machine/virtual_machine.py
    +++ b/source/usr/lib/mcvirt/virtual_machine/virtual_machine.py
    @@ -385,7 +385,7 @@ class VirtualMachine:
     
             # Update the MCVirt configuration
             def updateConfig(config):
    -            config['memory_allocation'] = memory_allocation
    +            config['memory_allocation'] = str(memory_allocation)
             self.getConfigObject().updateConfig(
                 updateConfig,
                 'RAM allocation has been changed to %s' %
