### ISSUE TITLE
Upgrade to python3

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#445]
Python 2.7 supports ends in 2020.

**Comment by MatthewJohn** [comment]
Given python2.7 ends support _this year_ (ish), this should be migrated ASAP

**Comment by MatthewJohn** [comment]
Issue from unit tests:

    ======================================================================
    ERROR: test_delete_non_existant_superuser (mcvirt.test.auth_tests.AuthTests)
    Attempts to remove a non-existent user from the superuser group.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/mcvirt/test/auth_tests.py", line 65, in setUp
        self.test_user = self.create_test_user(self.TEST_USERNAME, self.TEST_PASSWORD)
      File "/usr/lib/python3/dist-packages/mcvirt/test/auth_tests.py", line 48, in create_test_user
        self.user_factory.create(username, password)
      File "/usr/local/lib/python3.5/dist-packages/Pyro4/core.py", line 171, in __call__
        return self.__send(self.__name, args, kwargs)
      File "/usr/local/lib/python3.5/dist-packages/Pyro4/core.py", line 428, in _pyroInvoke
        raise data
    TypeError: b'5c95ba53716f70a4f67eacca8f0c74246b6a0c41d36575ccf0491674084d4563' is not JSON serializable
