### ISSUE TITLE
mcvirt base configuration directory is created with 600 permissions

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#67]
The directory should be set to 700 or 770. This causes issues when attempting to attach an ISO to the VM:

    root@node:~# mcvirt start vm --iso ubuntu-14.04.2-server-amd64.iso
    Attached ISO ubuntu-14.04.2-server-amd64.iso
    libvirt: QEMU Driver error : internal error: process exited while connecting to monitor: qemu-system-x86_64: -drive file=/var/lib/mcvirt/node/iso/ubuntu-14.04.2-server-amd64.iso,if=none,id=drive-ide0-1-0,readonly=on,format=raw: could not open disk image /var/lib/mcvirt/node/iso/ubuntu-14.04.2-server-amd64.iso: Could not open '/var/lib/mcvirt/node/iso/ubuntu-14.04.2-server-amd64.iso': Permission denied
    Traceback (most recent call last):
      File "/usr/bin/mcvirt", line 41, in <module>
        parser_object.parse_arguments()
      File "/usr/lib/mcvirt/parser.py", line 444, in parse_arguments
        vm_object.start(args.iso if args.iso else None)
      File "/usr/lib/mcvirt/virtual_machine/virtual_machine.py", line 202, in start
        self._getLibvirtDomainObject().create()
      File "/usr/lib/python2.7/dist-packages/libvirt.py", line 866, in create
        if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
    libvirt.libvirtError: internal error: process exited while connecting to monitor: qemu-system-x86_64: -drive file=/var/lib/mcvirt/node/iso/ubuntu-14.04.2-server-amd64.iso,if=none,id=drive-ide0-1-0,readonly=on,format=raw: could not open disk image /var/lib/mcvirt/node/iso/ubuntu-14.04.2-server-amd64.iso: Could not open '/var/lib/mcvirt/node/iso/ubuntu-14.04.2-server-amd64.iso': Permission denied

**Comment by MatthewJohn** [comment]
Manually changing the /var/lib/mcvirt directory to 700 fixes the issue

**Comment by MatthewJohn** [comment]
Fixed in cc827a3d7ce7e58b3cf7bf1ac4f6a0fdde8fecb9
