### ISSUE TITLE
Non-superusers receive exception about ignore_drbd

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#70]
Non-superusers receive the following exception when trying to run mcvirt:

    user@node:~$ sudo mcvirt list
    Traceback (most recent call last):
      File "/usr/bin/mcvirt", line 41, in <module>
        parser_object.parse_arguments()
      File "/usr/lib/mcvirt/parser.py", line 477, in parse_arguments
        if (args.ignore_drbd):

**Comment by MatthewJohn** [comment]
This is due to the 'ignore_drbd' argument only being added when the user has 'CAN_IGNORE_DRBD' permission
