### ISSUE TITLE
Removing a network from a VM throws an exception

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#95]
As originally reported by @sjs-itdev, see https://github.com/ITDevLtd/MCVirt/issues/53#issuecomment-117550691

Removing a network interface from a VM throws an exception:

    Traceback (most recent call last):
      File "/usr/bin/mcvirt", line 38, in <module>
        parser_object.parse_arguments()
      File "/usr/lib/mcvirt/parser.py", line 544, in parse_arguments
        network_adapter_object.delete()
      File "/usr/lib/mcvirt/virtual_machine/network_adapter.py", line 156, in delete
        vm_object.getConfigObject().updateConfig(
    NameError: global name 'vm_object' is not defined

**Comment by MatthewJohn** [comment]
Fixed in 8990481
