### ISSUE TITLE
Exception thrown when adding an ISO form a URL

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#98]
After running the command the first time, I received:

    user@node:~$ sudo mcvirt iso --add-from-url http://server-name/ubuntu-12.04.3-server-amd64.iso
    Traceback (most recent call last):
      File "/usr/bin/mcvirt", line 38, in <module>
        parser_object.parse_arguments()
      File "/usr/lib/mcvirt/parser.py", line 772, in parse_arguments
        output = Iso.addFromUrl(mcvirt_instance, args.add_url)
      File "/usr/lib/mcvirt/iso.py", line 90, in addFromUrl
        iso = urllib2.urlopen(url)
      File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
        return _opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 404, in open
        response = self._open(req, data)
      File "/usr/lib/python2.7/urllib2.py", line 422, in _open
        '_open', req)
      File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
        return self.do_open(httplib.HTTPConnection, req)
      File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
        r = h.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 409, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 373, in _read_status
        raise BadStatusLine(line)
    httplib.BadStatusLine: ''

The second time the command was run, I received:

    jb@node:~$ sudo mcvirt iso --add-from-url http://source-server.example.com/ubuntu-12.04.3-server-amd64.iso
    Traceback (most recent call last):
      File "/usr/bin/mcvirt", line 38, in <module>
        parser_object.parse_arguments()
      File "/usr/lib/mcvirt/parser.py", line 772, in parse_arguments
        output = Iso.addFromUrl(mcvirt_instance, args.add_url)
      File "/usr/lib/mcvirt/iso.py", line 104, in addFromUrl
        iso_object = Iso.addIso(mcvirt_instance, output_path)
      File "/usr/lib/mcvirt/iso.py", line 127, in addIso
        return Iso(filename)

After these, the ISO appeared to be present.

Some directories were left in /tmp with the iso in one of them.

**Comment by MatthewJohn** [comment]
Fixed in #100
